version: "3"

services:
  api:
    image: zaid450/service_monorepo_template
    env_file:
      - ./docker/api/api.env
  bot:
    image: zaid450/service_monorepo_template
    env_file:
      - ./docker/bot/bot.env
  pgdb:
    env_file:
      - ./docker/postgres/db.env
  gateway:
    env_file: 
      - ./docker/gateway/gateway.env